//This File is generated by github.com/MikkelHJuul/go-enum. DO NOT EDIT!
package main

type myEnumOrdinal int

const (
	HELLO0Ordinal myEnumOrdinal = 0
	HELLO2Ordinal myEnumOrdinal = 1
	HELLO3Ordinal myEnumOrdinal = 2
	HELLO4Ordinal myEnumOrdinal = 3
	HELLO5Ordinal myEnumOrdinal = 4
)

func HELLO0() eOne {
	return Values()[HELLO0Ordinal].(eOne)
}

func HELLO2() eTwo {
	return Values()[HELLO2Ordinal].(eTwo)
}

func HELLO3() eOne {
	return Values()[HELLO3Ordinal].(eOne)
}

func HELLO4() eOne {
	return Values()[HELLO4Ordinal].(eOne)
}

func HELLO5() eTwo {
	return Values()[HELLO5Ordinal].(eTwo)
}

func EnumMap() map[string]myEnum {
	return map[string]myEnum{
		"HELLO0": Values()[HELLO0Ordinal],
		"HELLO2": Values()[HELLO2Ordinal],
		"HELLO3": Values()[HELLO3Ordinal],
		"HELLO4": Values()[HELLO4Ordinal],
		"HELLO5": Values()[HELLO5Ordinal],
	}
}

func ValueOf(enumName string) (val myEnum, ok bool) {
	val, ok = EnumMap()[enumName]
	return
}
